### ISSUE TITLE
Filtering still seems to be broken

### ISSUE THREAD

**Issue by schafer21mcm** [fbaligand/kibana-enhanced-table#53]
Hi there,

Thanks again for the quick action on the last issue I reported. Unfortunately we are still seeing some odd results after the upgrade to v1.4 that had a fix for the below.

https://github.com/fbaligand/kibana-enhanced-table/issues/47

When I click the filter button on a value that is returned from a terms aggregation I am still seeing values other than what I click on get filtered. I'm wondering if it may have something to do with sorting? Previously I stated it only happened pages other than the first page of results but I'm even seeing issues on the first page.

Any additional help would be greatly appreciated!

Thanks,

**Comment by fbaligand** [comment]
Well, Indeed, I didn’t test with a custom sort. 
That Is probably the bug cause. 
I will test it...

**Comment by fbaligand** [comment]
Hi,

I just released a patch that fixes the issue:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.4.2

Hope that this time, it is the last one concerning "filtering".
Don't hesitate to test filtering in all ways and to push issues if you find another bug.

Fabien

**Comment by schafer21mcm** [comment]
Thanks for the quick turnaround on this. We've updated to the newest version but still seeing oddities when filtering by values. i.e. clicking one value to filter and a different value actually getting filtered. Not sure if we're missing something here? All the data gets returned correctly when using enhanced tables, it's just when we try to filter by a value thats returned when doing split rows...

**Comment by fbaligand** [comment]
I’m sad to heard it...
I use exactly the same way than official data table now. So I’m surprised it still doesn’t work.

Can you give me details about your issue. What buckets / metrics ? What options ? What computed / hidden columns ?
And what action you do to get the issue ? Sort, pagination, ... ?

**Comment by schafer21mcm** [comment]
I do some pretty complicated tables but this happens even when doing something simple like below.

![image](https://user-images.githubusercontent.com/5183332/62146358-d93fa980-b2ba-11e9-8bc9-fd00fab4ed4d.png)

![image](https://user-images.githubusercontent.com/5183332/62146407-f1172d80-b2ba-11e9-9a0d-16fdaf9e6037.png)

Just like the 1st issue I reported, filtering on the first page of terms aggregation results works just fine, but when I go to any other page, it starts filtering by the wrong value.

Kibana version - 7.1.0

Is there a way in the Kibana interface to see what version of the plugin we are using? We've installed the most recent one but I just want to make sure that's what I'm actually using in Kibana.

**Comment by fbaligand** [comment]
Thanks for the details.
Your visualization configuration looks very simple.
I made tests with one 'Spit Table' buckets + 2 'Split Rows' bucket, and pagination, and doesn't get issues. 
That said, I made my tests on Kibana 7.2.0. Maybe the issue is specific to 7.1 version.
But honestly, I would be surprised that the problem is specific to 7.1 version for this issue.

In kibana interface, you can get plugins list with version with this URL:
`<KIBANA_URL>/status`
You can also look at $KIBANA_HOME/plugins/enhanced-table/package.json and check "version" field.
Can you check you use 'enhanced-table' version 1.4.2?

**Comment by schafer21mcm** [comment]
Yep, we are on "version": "1.4.2".

**Comment by fbaligand** [comment]
Well, I’m confused, because I don’t manage to reproduce your issue...

**Comment by siddharth99** [comment]
I am also facing an issue with filtering values; I recently upgraded from 6.5 to 7.3 and after upgrade when I click the + icon for filtering - I get the below kibana error
```
TypeError: visFilters.filter is not a function (http://localhost:8888/bundles/commons.bundle.js:3)

Version: 7.3.0
Build: 25250
Error: TypeError: visFilters.filter is not a function (http://localhost:8888/bundles/commons.bundle.js:3)
window.onerror@http://localhost:8888/bundles/commons.bundle.js:3:1886568
```
I don't get the error using any other in-built visualization.

**Comment by fbaligand** [comment]
Hi, this is a quite different issue. 
This issue should arrive only if you did not install 1.4.3_7.3.0 package. 

So, could you install this package:
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.4.3/enhanced-table-1.4.3_7.3.0.zip

**Comment by siddharth99** [comment]
You are correct, when I tried out Kibana 7.3 I just copied the 1.4.2_7.2.0 package and edited it's version number from 7.2 to 7.3 manually since 1.4.3 was not out then. But later I removed 1.4.2_7.2.0 and installed 1.4.3_7.3.0 but even after installing the newer plugin I am still getting a similar error not quite exactly the same though; I tried restarting / clearing browser cache etc but still get this error.. any ideas on how to fix this now:
```
Uncaught TypeError: visFilters.filter is not a function (http://localhost:8888/built_assets/dlls/vendors.bundle.dll.js:76)
Version: 7.3.0
Build: 25250
Error: Uncaught TypeError: visFilters.filter is not a function (http://localhost:8888/built_assets/dlls/vendors.bundle.dll.js:76)
    at window.onerror (http://localhost:8888/bundles/commons.bundle.js:3:1886568)
```

**Comment by fbaligand** [comment]
Well, to be sure of the install, I invite you to do these actions:
- stop Kibana 
- remove plugins/enhanced-table and optimize folders
- install enhanced table v1.4.3
- restart Kibana
- refresh your browser.

**Comment by siddharth99** [comment]
Great, clearing the optimize folder worked. Thanks!

**Comment by fbaligand** [comment]
Nice!
Thanks for your feedback :)

**Comment by fbaligand** [comment]
Last version should fix the issue.
